version: 0.0
os: linux
files:
  - source: /
    destination: /var
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2_user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2_user
