version: 0.2
phases:
 install:
   runtime-versions:
      nodejs: 10
   commands:
     - echo "install step"
 build:
   commands:
     - npm run-script build
 post_build:
   commands:
     - echo "Build Done"
