version: 0.2
phases:
 install:
   runtime-versions:
      nodejs: 10
   commands:
     - echo "install step"
 build:
   commands:
     - echo "build step"
 post_build:
   commands:
     - echo "post_build step"
