version: 0.2
phases:
 install:
   runtime-versions:
      nodejs: 10
   commands:
     - echo "install step"
     - npm install
     - npm install -g @angular/cli
 build:
   commands:
     - npm run-script build
 post_build:
   commands:
     - aws s3 sync --delete ./dist/superfinder "s3://seekandfind-hosting"
